// iOS Deployment Configuration
const IPHONEOS_DEPLOYMENT_TARGET = "13.0";
const TARGETED_DEVICE_FAMILY = `"1,2"`;

// Template Regex Patterns
const BUNDLE_SHORT_VERSION_TEMPLATE_REGEX = /{{BUNDLE_SHORT_VERSION}}/gm;
const BUNDLE_VERSION_TEMPLATE_REGEX = /{{BUNDLE_VERSION}}/gm;
const CATEGORY_IDENTIFIER_TEMPLATE_REGEX = /{{CATEGORY_IDENTIFIER}}/gm;
const CONTENT_SIZE_RATIO_TEMPLATE_REGEX = /{{CONTENT_SIZE_RATIO}}/gm;

// Default Values
const DEFAULT_BUNDLE_VERSION = '1';
const DEFAULT_BUNDLE_SHORT_VERSION = '1.0';
const DEFAULT_CATEGORY_IDENTIFIER = 'CGMSIM_RICH_NOTIFICATION';
const DEFAULT_CONTENT_SIZE_RATIO = 0.5;

// Extension Configuration
const NCE_TARGET_NAME = "NotificationContentExtension";
const NCE_SOURCE_FILES = [
    "NotificationViewController.h",
    "NotificationViewController.m"
];
const NCE_RESOURCE_FILES = [
    "MainInterface.storyboard"
];
const NCE_EXT_FILES = [
    `${NCE_TARGET_NAME}-Info.plist`
    // Entitlements not needed for simple content extension
];

module.exports = {
    IPHONEOS_DEPLOYMENT_TARGET,
    TARGETED_DEVICE_FAMILY,
    BUNDLE_SHORT_VERSION_TEMPLATE_REGEX,
    BUNDLE_VERSION_TEMPLATE_REGEX,
    CATEGORY_IDENTIFIER_TEMPLATE_REGEX,
    CONTENT_SIZE_RATIO_TEMPLATE_REGEX,
    DEFAULT_BUNDLE_VERSION,
    DEFAULT_BUNDLE_SHORT_VERSION,
    DEFAULT_CATEGORY_IDENTIFIER,
    DEFAULT_CONTENT_SIZE_RATIO,
    NCE_TARGET_NAME,
    NCE_SOURCE_FILES,
    NCE_RESOURCE_FILES,
    NCE_EXT_FILES
};
